validate PORTRULES

diff --git a/files/natter.init b/files/natter.init
--- a/files/natter.init
+++ b/files/natter.init
@@ -33,6 +33,19 @@ validate_section() {
 		'udp_stun:list(host)'
 }
 
+validate_section_portrule() {
+	uci_load_validate $CONFIG_NAME $PORTRULES "$1" "$2" \
+		'enabled:bool:0' \
+		'comment:string' \
+		'action:or("bind", "forward"):bind' \
+		'mode:or("dnat", "via"):dnat' \
+		'bind_iface:list(network)' \
+		'bind_port:range(1, 65535)' \
+		'server_ip:ip4addr(1):127.0.0.1' \
+		'server_port:range(1, 65535)' \
+		'proto:or("udp", "tcp", "both"):both'
+}
+
 # check_nat [port]
 check_nat() {
 	local n="$(${CHECK} $1 | base64)"
@@ -97,42 +110,34 @@ init_natter() {
 
 }
 
-apply_port_rules() {
-	local rule_count=$(uci show $CONFIG_NAME|grep "$PORTRULES"|tail -n1|sed -En "s|.+@.+\[(.+)\].+|\1|p")
-	local open_port_list_tcp open_port_list_udp forward_port_list_tcp forward_port_list_udp
+apply_port_rules_genlist() {
+	[ "$2" == "0" ] || { >&2 echo "section $1 validation failed"; return 1; }
+	[ "$enabled" == "0" ] && return 0
+	[ "$mode" == "via" -a "$NAT_TYPE" == "#" ] && return 0
 
-for i in $(seq 0 1 $rule_count); do
-	[ "$(uci -q get $CONFIG_NAME.@$PORTRULES[$i].enabled)" == "0" ] && continue
-	[ "$(uci -q get $CONFIG_NAME.@$PORTRULES[$i].mode)" == "via" -a "$NAT_TYPE" == "#" ] && continue
-
-	local ucivv="comment action mode bind_ifaces bind_port server_ip server_port proto"
-	for _var in $ucivv; do
-		eval "local $_var=\$(uci -q get $CONFIG_NAME.@$PORTRULES[$i].$_var)"
-	done
-	local bind_iface bind_ip id protocols
-	id=$(uci show $CONFIG_NAME.@$PORTRULES[$i] 2>/dev/null|head -n1|sed -E 's|.+\.(cfg[^=]+)=.+|\1|')
-	[ -z "$bind_ifaces" ] && bind_ifaces='none'
+	local iface bind_ip id=$1 protocols
+	[ -z "$bind_iface" ] && bind_iface='none'
 	[ "$proto" == "both" ] && protocols="tcp udp" || protocols="$proto"
 
-for bind_iface in $bind_ifaces; do
+for iface in $bind_iface; do
 
-	[ "$bind_iface" == "none" ] && bind_iface=''
-	[ -z "$bind_iface" ] && bind_ip='0.0.0.0' || bind_ip="$(ip -4 -o addr|grep "$bind_iface"|sed -En "s|.+inet ([^/]+)/\d{2}.+|\1|p")"
+	[ "$iface" == "none" ] && iface=''
+	[ -z "$iface" ] && bind_ip='0.0.0.0' || bind_ip="$(ip -4 -o addr|grep "$iface"|sed -En "s|.+inet ([^/]+)/\d{1,2}.+|\1|p")"
 	[ -z "$bind_ip" ] && continue
 
 for proto in $protocols; do
 	if   [ "$action" == "bind" ]; then
-		# white open_port action==bind id comment *bind_iface bind_port proto
+		# white open_port action==bind id comment *iface bind_port proto
 		eval "open_port_list_$proto=\"\$open_port_list_$proto'\${bind_ip}:\${bind_port}'\n\""
 		# set firewall
-		white_fw_rule 'input' "$id" "$comment" "$proto" "$bind_iface" "$bind_ip" "$bind_port"
+		white_fw_rule 'input' "$id" "$comment" "$proto" "$iface" "$bind_ip" "$bind_port"
 	elif [ "$action" == "forward" ]; then
 		if   [ "$mode" == "dnat" ]; then
-			# white forward_port action==forward mode==dnat id comment *bind_iface bind_port proto server_ip server_port
+			# white forward_port action==forward mode==dnat id comment *iface bind_port proto server_ip server_port
 			eval "open_port_list_$proto=\"\$open_port_list_$proto'\${bind_ip}:\${bind_port}'\n\""
 			# set firewall
 			[ -z "$server_ip" ] && >&2 echo -e "$(basename $0): server_ip is empty." && return 1
-			white_fw_rule 'dnat' "$id" "$comment" "$proto" "$bind_iface" "$bind_ip" "$bind_port" "$server_ip" "$server_port"
+			white_fw_rule 'dnat' "$id" "$comment" "$proto" "$iface" "$bind_ip" "$bind_port" "$server_ip" "$server_port"
 		elif [ "$mode" == "via" ]; then
 			# white forward_port action==forward mode==via id comment proto server_ip server_port
 			[ "$server_ip" == "0.0.0.0" ] && server_ip='127.0.0.1'
@@ -142,8 +147,12 @@ for proto in $protocols; do
 done
 
 done
+}
 
-done
+apply_port_rules() {
+	local open_port_list_tcp open_port_list_udp forward_port_list_tcp forward_port_list_udp
+
+	config_foreach validate_section_portrule "$PORTRULES" apply_port_rules_genlist || return $?
 
 # white conf
 sed -Ei "$(sed -En "/\"open_port\": \{/,/\},*$/{ /\"tcp\": \[/=}" "$CONF")a\ $(echo $(echo -e "$open_port_list_tcp"|sort -u)|sed "s|' '|',\\\n            '|g; s|^'|           '|; s|'|\"|g")" "$CONF"
@@ -295,7 +304,7 @@ start_service() {
 
 	`check_nat` && NAT_TYPE=1 || NAT_TYPE=#
 	init_natter 1 || return $?
-	apply_port_rules
+	apply_port_rules || return $?
 	[ $? == 0 ] && natter_launch
 }
 
